### ISSUE TITLE
Checklist for BMI v2.1 release

### ISSUE THREAD

**Issue by mdpiper** [csdms/bmi#81]
Although only a few functions will be added in BMI v2.1, doing so will set off a series of updates for downstream products. This issue lists those updates.

- [ ] Complete all tasks for [BMI 2.1 milestone](https://github.com/csdms/bmi/milestone/1)
- [ ] Update [documentation](https://bmi.readthedocs.io)
- [ ] Update language specifications (C, C++, Fortran, Python), including conda-forge recipes
- [ ] Update example implementations (C, C++, Fortran, Python), including new tests
- [ ] Create new example implementations (if we add Octave and R specifications as planned)
- [ ] Add BMI v2.1 functions to the language templates in the *babelizer* (this may also require a new `--bmi-version` option)
- [ ] Add BMI v2.1 functions to the *bmi-tester* (and update `--bmi-version` option)
- [ ] Add BMI v2.1 functions to *pymt*
